### ISSUE TITLE
数据集找不到

### ISSUE THREAD

**Issue by yuxiazff** [ZhengyuZhao/koniq-PyTorch#3]
你好，请问你还有这个数据集吗，这个网址打不开了http://datasets.vqa.mmsp-kn.de/archives/koniq10k_512x384.zip

**Comment by yuxiazff** [comment]
我终于找到这个数据了，在官方的git仓库的问题中有关于数据集的回答，这个问题的链接是：https://github.com/subpic/koniq/issues/5

数据集的地址是https://osf.io/hcsdy/
下载如下图的文件即可
![image](https://user-images.githubusercontent.com/5620313/186559735-220de080-d5d3-49d8-920e-b7dbf8bbbec1.png)

**Comment by cloverzyy** [comment]
> 我终于找到这个数据了，在官方的git仓库的问题中有关于数据集的回答，这个问题的链接是：[subpic/koniq#5](https://github.com/subpic/koniq/issues/5)
> 
> 数据集的地址是https://osf.io/hcsdy/ 下载如下图的文件即可 ![image](https://user-images.githubusercontent.com/5620313/186559735-220de080-d5d3-49d8-920e-b7dbf8bbbec1.png)

您好，我在https://osf.io/hcsdy/下载到的224*224的图像有10373张，1024*768的图像有5454张，但是koniq10k_scores表格里面的数据是10074条，标签和图像对不上，这个情况您怎么处理的呢？

**Comment by yuxiazff** [comment]
@cloverzyy  你好，我是把koniq10k_scores.csv里面没有出现的那些图片删掉了的。

**Comment by cloverzyy** [comment]
这是来自QQ邮箱的假期自动回复邮件。来信已收到，辛苦各位啦！
